name: xcode build test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-15', 'macos-15-large']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Xcode version
      run: xcodebuild -version

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer

    - name: List all available simulators (debugging)
      run: |
        echo "Listing all available simulators..."
        xcrun simctl list devices

    - name: Create iPhone 15 pro simulator if not exists
      run: |
        DEVICE_TYPE=$(xcrun simctl list devicetypes | grep -i "iPhone 15 Pro" | awk -F '[()]' '{print $2}')
        RUNTIME=$(xcrun simctl list runtimes | grep -i "iOS" | grep -v "unavailable" | head -n 1 | awk -F '[()]' '{print $2}')
        if ! xcrun simctl list devices | grep -q "iPhone 15 pro"; then
          echo "Creating iPhone 15 pro simulator with device type $DEVICE_TYPE and runtime $RUNTIME..."
          xcrun simctl create "iPhone 15 pro" $DEVICE_TYPE $RUNTIME
        fi

    - name: Build with xcodebuild
      run: xcodebuild -project sim.xcodeproj -scheme sim -destination 'platform=iOS Simulator,name=iPhone 15 pro'
