name: xcode build test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-15-xlarge']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build with xcodebuild
      run: xcodebuild -project sim.xcodeproj -scheme sim -destination 'platform=iOS Simulator,name=iPhone 12'
        
    - name: List all available simulators (debugging)
      run: |
        echo "Listing all available simulators..."
        # List all simulators without filtering to debug output
        xcrun simctl list devices
   


  
