name: xcode build test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-15-xlarge', 'macos-15-large']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Xcode version
      run: xcodebuild -version

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer

    - name: List all available simulators (debugging)
      run: |
        echo "Listing all available simulators..."
        xcrun simctl list devices

    - name: Create iPhone 15 pro simulator if not exists
      run: |
        if ! xcrun simctl list devices | grep -q "iPhone 15 pro"; then
          echo "Creating iPhone 15 pro simulator..."
          xcrun simctl create "iPhone 15 pro" com.apple.CoreSimulator.SimDeviceType.iPhone-15-pro com.apple.CoreSimulator.SimRuntime.iOS-16-2
        fi

    - name: Build with xcodebuild
      run: xcodebuild -project sim.xcodeproj -scheme sim -destination 'platform=iOS Simulator,name=iPhone 15 pro'


  
